knowledge_base_path:
id: DataModel
name: DataModel
description: A combined schema model for MOCK_DATA and Chinook Data.
prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://example.org/

default_prefix: ex

types:
  integer:
    base: integer
  float:
    base: float

classes:

  Person:
    description: "A person record from MOCK_DATA."
    attributes:
      id:
        description: The unique identifier of a person.
        identifier: true
        range: integer
      first_name:
        description: The first name of the person.
        range: string
      last_name:
        description: The last name of the person.
        range: string
      email:
        description: The email of the person.
        range: string
        pattern: "[^@]+@[^@]+\.[^@]+"
      gender:
        description: The gender of the person.
        range: string
      ip_address:
        description: The IP address of the person.
        range: string
        pattern: "(\d{1,3}\.){3}\d{1,3}"

  Genre:
    description: "Music genre information."
    attributes:
      GenreId:
        identifier: true
        range: integer
      Name:
        description: The name of the genre.
        range: string

  MediaType:
    description: "Media type information."
    attributes:
      MediaTypeId:
        identifier: true
        range: integer
      Name:
        description: The name of the media type.
        range: string

  Artist:
    description: "Artist information."
    attributes:
      ArtistId:
        identifier: true
        range: integer
      Name:
        description: The name of the artist.
        range: string

  Album:
    description: "Album information."
    attributes:
      AlbumId:
        identifier: true
        range: integer
      Title:
        description: The title of the album.
        range: string
      ArtistId:
        range: integer
        description: Reference to the artist of the album.

  Track:
    description: "Track information."
    attributes:
      TrackId:
        identifier: true
        range: integer
      Name:
        description: The name of the track.
        range: string
      AlbumId:
        range: integer
        description: Reference to the album containing the track.
      GenreId:
        range: integer
        description: Reference to the genre of the track.
      MediaTypeId:
        range: integer
        description: Reference to the media type.
      Composer:
        description: The composer of the track.
        range: string
        required: false
      Milliseconds:
        description: Duration of the track in milliseconds.
        range: integer
      Bytes:
        description: Size of the track in bytes.
        range: integer
        required: false
      UnitPrice:
        description: The price of the track.
        range: float

  Customer:
    description: "Customer information."
    attributes:
      CustomerId:
        identifier: true
        range: integer
      FirstName:
        description: The first name of the customer.
        range: string
      LastName:
        description: The last name of the customer.
        range: string
      Company:
        description: The company of the customer, if any.
        range: string
        required: false
      Address:
        description: Address of the customer.
        range: string
      City:
        description: City of the customer.
        range: string
      State:
        description: State of the customer.
        range: string
        required: false
      Country:
        description: Country of the customer.
        range: string
      PostalCode:
        description: Postal code of the customer's address.
        range: string
        required: false
      Phone:
        description: Phone number of the customer.
        range: string
        required: false
      Fax:
        description: Fax number of the customer.
        range: string
        required: false
      Email:
        description: The email of the customer.
        range: string
        pattern: "[^@]+@[^@]+\.[^@]+"
      SupportRepId:
        range: integer
        description: Reference to the support representative.

  Employee:
    description: "Employee information."
    attributes:
      EmployeeId:
        identifier: true
        range: integer
      FirstName:
        description: The first name of the employee.
        range: string
      LastName:
        description: The last name of the employee.
        range: string
      Title:
        description: The job title of the employee.
        range: string
      BirthDate:
        description: The birthdate of the employee.
        range: string
      HireDate:
        description: The hire date of the employee.
        range: string
      Address:
        description: The address of the employee.
        range: string
      City:
        description: City of the employee.
        range: string
      State:
        description: State of the employee.
        range: string
        required: false
      Country:
        description: Country of the employee.
        range: string
      PostalCode:
        description: Postal code of the employee's address.
        range: string
        required: false
      Phone:
        description: Phone number of the employee.
        range: string
        required: false
      Fax:
        description: Fax number of the employee.
        range: string
        required: false
      Email:
        description: The email of the employee.
        range: string
        pattern: "[^@]+@[^@]+\.[^@]+"
      ReportsTo:
        range: integer
        description: Reference to other employee this employee reports to.
        required: false

  Invoice:
    description: "Invoice information."
    attributes:
      InvoiceId:
        identifier: true
        range: integer
      CustomerId:
        range: integer
        description: Reference to the customer of the invoice.
      InvoiceDate:
        description: The date of the invoice.
        range: string
      BillingAddress:
        description: Billing address.
        range: string
      BillingCity:
        description: Billing city.
        range: string
      BillingState:
        description: Billing state.
        range: string
        required: false
      BillingCountry:
        description: Billing country.
        range: string
      BillingPostalCode:
        description: Postal code for billing.
        range: string
        required: false
      Total:
        description: Total amount of the invoice.
        range: float

  InvoiceLine:
    description: "Details of each invoice line."
    attributes:
      InvoiceLineId:
        identifier: true
        range: integer
      InvoiceId:
        range: integer
        description: Reference to associated invoice.
      TrackId:
        range: integer
        description: Reference to the track sold.
      UnitPrice:
        description: Price per unit of item.
        range: float
      Quantity:
        description: Number of units sold.
        range: integer

  Playlist:
    description: "Playlist information."
    attributes:
      PlaylistId:
        identifier: true
        range: integer
      Name:
        description: The name of the playlist.
        range: string

  PlaylistTrack:
    description: "Tracks included in a playlist."
    attributes:
      PlaylistId:
        range: integer
        description: Reference to the playlist.
      TrackId:
        range: integer
        description: Reference to the track.