services:
  postgres:
    image: postgres:15
    container_name: langchain_postgres
    restart: always
    environment:
      POSTGRES_USER: langchain_user
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: langchain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
      - ./knowledge_base/temp:/knowledge_base/temp

  pgadmin:
    image: dpage/pgadmin4
    container_name: langchain_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain_python_app
    restart: "no"   # je nach Usecase kannst du hier always, on-failure oder no nehmen
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["python", "main.py"]

volumes:
  pgdata:
  pgadmin_data:
